pycham_test/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('create/', views.create_post, name='create'),
    path('<int:post_id>/', views.get_post, name='read'),
    path('<int:post_id>/update/', views.update_post, name='create'),
    path('<int:post_id>/delete', views.delete_post, name='delete'),
    path('<int:post_id>/download/', views.download_post, name='download'),
    path('', views.get_posts, name='list'),

]

pycham_test/pycham_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('posts/', include('posts.urls')),
]

pycham_test/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(verbose_name="제목", max_length=100)
    content = models.TextField(verbose_name="내용")
    password = models.CharField(verbose_name="비밀번호", max_length=100)
    username = models.CharField(verbose_name="글쓴이", max_length=10)
    filename = models.CharField(verbose_name="파일명", max_length=100, null=True, blank=True)
    original_filename = models.CharField(verbose_name="원본파일명", max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(verbose_name="작성일시", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="수정일시", auto_now=True)

    class Meta:
        db_table = "posts"
        verbose_name = "게시글"
        verbose_name_plural = "게시글 목록"

    def __str__(self):
        return self.title

pycham_test/posts/forms.py
from django import forms
from .models import Post
# 게시글 등록 폼
class PostCreateForm(forms.ModelForm):
    title = forms.CharField(required=False)
    content = forms.CharField(required=False)
    username = forms.CharField(required=False)
    password = forms.CharField(required=False)

    class Meta:
        model = Post
        fields = ['title', 'content', 'password', 'username']

    # 제목 검증
    def clean_title(self):
        title = self.cleaned_data['title']
        if not title:
            raise forms.ValidationError("제목을 입력해주세요.")
        if len(title) < 2:
            raise forms.ValidationError("제목은 최소 2자 이상 입력해주세요.")
        if len(title) > 100:
            raise forms.ValidationError("제목은 최대 100자 이하로 입력해주세요.")
        return title

    # 내용 검증
    def clean_content(self):
        content = self.cleaned_data['content']
        if not content:
            raise forms.ValidationError("내용을 입력해주세요.")
        return content

    # 비밀번호 검증
    def clean_password(self):
        password = self.cleaned_data['password']
        if not password:
            raise forms.ValidationError("비밀번호를 입력해주세요.")
        if len(password) < 4:
            raise forms.ValidationError("비밀번호는 최소 4자 이상 입력해주세요.")
        if len(password) > 20:
            raise forms.ValidationError("비밀번호는 최대 20자 이하로 입력해주세요.")
        return password

    # 글쓴이 검증
    def clean_username(self):
        username = self.cleaned_data['username']
        if not username:
            raise forms.ValidationError("글쓴이를 입력해주세요.")
        if len(username) < 2:
            raise forms.ValidationError("글쓴이는 최소 2자 이상 입력해주세요.")
        if len(username) > 10:
            raise forms.ValidationError("글쓴이는 최대 10자 이하로 입력해주세요.")
        return username

# 게시글 수정 폼
class PostUpdateForm(forms.ModelForm):
    title = forms.CharField(required=False)
    content = forms.CharField(required=False)
    username = forms.CharField(required=False)
    password = forms.CharField(required=False)

    class Meta:
        model = Post
        fields = ['title', 'content', 'password', 'username']

    # 제목 검증
    def clean_title(self):
        title = self.cleaned_data['title']
        if not title:
            raise forms.ValidationError("제목을 입력해주세요.")
        if len(title) < 2:
            raise forms.ValidationError("제목은 최소 2자 이상 입력해주세요.")
        if len(title) > 100:
            raise forms.ValidationError("제목은 최대 100자 이하로 입력해주세요.")
        return title

    # 내용 검증
    def clean_content(self):
        content = self.cleaned_data['content']
        if not content:
            raise forms.ValidationError("내용을 입력해주세요.")
        return content

    # 비밀번호 검증
    def clean_password(self):
        password = self.cleaned_data['password']
        if not password:
            raise forms.ValidationError("비밀번호를 입력해주세요.")
        if len(password) < 4:
            raise forms.ValidationError("비밀번호는 최소 4자 이상 입력해주세요.")
        if len(password) > 20:
            raise forms.ValidationError("비밀번호는 최대 20자 이하로 입력해주세요.")
        return password

    # 글쓴이 검증
    def clean_username(self):
        username = self.cleaned_data['username']
        if not username:
            raise forms.ValidationError("글쓴이를 입력해주세요.")
        if len(username) < 2:
            raise forms.ValidationError("글쓴이는 최소 2자 이상 입력해주세요.")
        if len(username) > 10:
            raise forms.ValidationError("글쓴이는 최대 10자 이하로 입력해주세요.")
        return username

pycham_test/posts/views.py
import os
import uuid
from urllib.parse import quote

from pycham_test import settings

from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.hashers import make_password,check_password

from .forms import PostCreateForm,PostUpdateForm
from .models import Post


# Create your views here.
# 이미지 분류
def image_test(request):
    predict=data_pro()
    return render(request, 'imagePro/image_test.html',
                  {"predict":predict,"MEDIA_URL":settings.MEDIA_URL})

def image_test2(request):

    predict=data_pro()
    return render(request, 'imagePro/image_test.html',
                  {"predict":predict,"MEDIA_URL":settings.MEDIA_URL})

# 게시글 등록

def create_post2(request):
    form = PostCreateForm()


    if request.method == 'POST':
        form = PostCreateForm(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            post.password = make_password(form.cleaned_data['password'])
            post.save()

            # 파일 업로드
            if request.FILES['uploadFile']:
                filename = uuid.uuid4().hex
                file = request.FILES['uploadFile']

                # 파일 저장 경로
                file_path = os.path.join(settings.MEDIA_ROOT, 'posts', str(post.id), str(filename))
                if not os.path.exists(os.path.dirname(file_path)):
                    os.makedirs(os.path.dirname(file_path))

                # 파일 저장
                save_path=file_path+file.name
                with open(save_path, 'wb') as f:
                    for chunk in file.chunks():
                        f.write(chunk)

                post.filename = filename
                post.original_filename = file.name
                post.save()

                predict = data_pro2(filename, post.id, file.name)
                print(predict)

            messages.success(request, '게시글이 등록되었습니다.')
            return render(request, "imagePro/image_test2.html", {"predict":predict,"savepath":save_path})
        else:
            messages.error(request, '게시글 등록에 실패했습니다.')
    return render(request,'posts/create.html',{'form':form})


def create_post(request):
    form = PostCreateForm()

    if request.method == 'POST':
        form = PostCreateForm(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            post.password = make_password(form.cleaned_data['password'])
            post.save()

            # 파일 업로드
            if request.FILES['uploadFile']:
                filename = uuid.uuid4().hex
                file = request.FILES['uploadFile']

                # 파일 저장 경로
                file_path = os.path.join(settings.MEDIA_ROOT, 'posts', str(post.id), str(filename))
                if not os.path.exists(os.path.dirname(file_path)):
                    os.makedirs(os.path.dirname(file_path))

                # 파일 저장
                save_path=file_path+file.name
                with open(save_path, 'wb') as f:
                    for chunk in file.chunks():
                        f.write(chunk)

                post.filename = filename
                post.original_filename = file.name
                post.save()

            messages.success(request, '게시글이 등록되었습니다.')
            return redirect("posts:read", post_id=post.id)
        else:
            messages.error(request, '게시글 등록에 실패했습니다.')
    return render(request,'posts/create.html',{'form':form})

# 게시글 보기
def get_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    return render(request, 'posts/read.html', {'post': post})

# 게시글 수정
def update_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post_password = post.password
    form = PostUpdateForm(instance=post)

    if request.method == 'POST':
        form = PostUpdateForm(request.POST)

        if form.is_valid():
            if check_password(form.cleaned_data['password'] == post.password):
                post = form.save(commit=False)
                post.password = make_password(form.cleaned_data['password'])
                post.save()

                # 파일 삭제
                if form.cleaned_data['deleteFile']:
                    if post.filename:
                        # 파일 삭제
                        file_path = os.path.join(settings.MEDIA_ROOT, 'posts', str(post.id), str(post.filename))
                        if os.path.exists(file_path):
                            os.remove(file_path)

                        post.filename = None
                        post.original_filename = None
                        post.save()

                # 파일 업로드
                if request.FILES['uploadFile']:
                    if post.filename:
                        # 파일 삭제
                        file_path = os.path.join(settings.MEDIA_ROOT, 'posts', str(post.id), str(post.filename))
                        if os.path.exists(file_path):
                            os.remove(file_path)

                    filename = uuid.uuid4().hex
                    file = request.FILES['uploadFile']

                    # 파일 저장 경로
                    file_path = os.path.join(settings.MEDIA_ROOT, 'posts', str(post.id), str(filename))
                    if not os.path.exists(os.path.dirname(file_path)):
                        os.makedirs(os.path.dirname(file_path))

                    # 파일 저장
                    with open(file_path, 'wb') as f:
                        for chunk in file.chunks():
                            f.write(chunk)

                    post.filename = filename
                    post.original_filename = file.name
                    post.save()



                messages.success(request, '게시글이 수정되었습니다.')
                return redirect('posts:read', post_id=post.id)
            else:
                messages.error(request, '비밀번호가 일치하지 않습니다.')
        else:
            messages.error(request, '게시글 수정에 실패했습니다.')

    return render(request, 'posts/update.html', {'form': form})

# 게시글 삭제
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    password = request.POST.get('password')

    if request.method == 'POST':
        if check_password(password == post.password):

            # 파일 삭제
            if post.filename:
                file_path = os.path.join(settings.MEDIA_ROOT, 'posts', str(post.id), str(post.filename))
                if os.path.exists(file_path):
                    os.remove(file_path)

            post.delete()
            messages.success(request, '게시글이 삭제되었습니다.')
            return redirect('posts:list')
        else:
            messages.error(request, '비밀번호가 일치하지 않습니다.')
            return redirect('posts:read', post_id=post.id)

# 게시글 목록
def get_posts(request):
    page = request.GET.get('page', '1')
    searchType = request.GET.get('searchType')
    searchKeyword = request.GET.get('searchKeyword')
    posts = Post.objects.all().order_by('-created_at')

    # 검색 조건 처리
    if searchType not in [None, ''] and searchKeyword not in [None, '']:
        if searchType == 'all':
            posts = posts.filter(
                Q(title__contains=searchKeyword) |
                Q(content__contains=searchKeyword) |
                Q(username__contains=searchKeyword)
            )
        elif searchType == 'title':
            posts = posts.filter(
                Q(title__contains=searchKeyword)
            )
        elif searchType == 'content':
            posts = posts.filter(
                Q(content__contains=searchKeyword)
            )
        elif searchType == 'username':
            posts = posts.filter(
                Q(username__contains=searchKeyword)
            )

    # 페이지네이션
    paginator = Paginator(posts, 10)
    page_obj = paginator.get_page(page)

    # 현재 페이지의 첫 번째 게시글 번호 계산
    start_index = paginator.count - (paginator.per_page * (page_obj.number - 1))

    # 순번 계산하여 게시글 리스트에 추가
    for index, _ in enumerate(page_obj, start=0):
        page_obj[index].index_number = start_index - index

    return render(request, 'posts/list.html', {
        'posts': page_obj,
        'searchType': searchType,
        'searchKeyword': searchKeyword,
    })

# 첨부 파일 다운로드
def download_file(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    file_path = os.path.join(settings.MEDIA_ROOT, 'posts', str(post.id), str(post.filename))

    if os.path.exists(file_path):
        with open(file_path, 'rb') as file:
            response = HttpResponse(file.read(), content_type='application/octet-stream')
            encoded_filename = quote(post.original_filename)
            response['Content-Disposition'] = f'attachment; filename*=UTF-8\'\'{encoded_filename}'
            return response

    return HttpResponse(status=404)

pycham_test/templates/posts/create.html
{% extends "../base.html" %}

{% block content %}
<div class="row">
    <div class="col-12">
        <!-- 게시글 등록 -->
        <form id="createForm" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card mb-3">
                <div class="card-header">
                    <span class="text-danger">*</span> 표시는 필수항목입니다.
                </div>
                <div class="card-body">            
                    <div class="mb-3">
                        <label for="title" class="form-label">제목 <span class="text-danger">*</span></label>
                        <input type="text" id="title" name="title" class="form-control" placeholder="제목을 입력하세요." value="{{ form.title.value|default_if_none:'' }}">
                        {% if form.title.errors %}
                        <div class="form-text text-danger">
                            {{ form.title.errors.0 }}
                        </div>
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="content" class="form-label">내용 <span class="text-danger">*</span></label>
                        <textarea rows="10" id="content" name="content" class="form-control" placeholder="내용을 입력하세요.">{{ form.content.value|default_if_none:'' }}</textarea>
                        {% if form.content.errors %}
                        <div class="form-text text-danger">
                            {{ form.content.errors.0 }}
                        </div>
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="username" class="form-label">글쓴이 <span class="text-danger">*</span></label>
                        <input type="text" id="username" name="username" class="form-control" placeholder="글쓴이를 입력하세요." value="{{ form.username.value|default_if_none:'' }}">
                        {% if form.username.errors %}
                        <div class="form-text text-danger">
                            {{ form.username.errors.0 }}
                        </div>
                        {% endif %}
                    </div>
                    <div>
                        <label for="password" class="form-label">비밀번호 <span class="text-danger">*</span></label>
                        <input type="password" id="password" name="password" class="form-control" placeholder="비밀번호를 입력하세요.">
                        {% if form.password.errors %}
                        <div class="form-text text-danger">
                            {{ form.password.errors.0 }}
                        </div>
                        {% endif %}
                    </div>
                </div>                
            </div>
            <div>
                 <label for="uploadFile" class="form-label">첨부 파일</label>
                 <input type="file" class="form-control" id="uploadFile" name="uploadFile" accept="image/*">
            </div>
            <div>
                <button type="submit" class="btn btn-primary">등록</button>
                <a href="{% url 'testapp:list' %}" class="btn btn-secondary">취소</a>
            </div>
        </form>
        <!--// 게시글 등록 -->
    </div>
</div>
{% endblock %}

pycham_test/templates/posts/list.html
{% extends "../base.html" %}

{% block content %}
<div class="row">
    <div class="col-12">    
        <!-- 검색, 등록 버튼 -->
        <div class="d-flex justify-content-between">
            <!-- 검색 폼 -->
            <form method="GET">
                <div class="input-group">
                    <select name="searchType" class="form-select w-auto">
                        <option value="all" {% if searchType == 'all' %}selected{% endif %}>전체</option>
                        <option value="title" {% if searchType == 'title' %}selected{% endif %}>제목</option>
                        <option value="content" {% if searchType == 'content' %}selected{% endif %}>내용</option>
                        <option value="username" {% if searchType == 'username' %}selected{% endif %}>작성자</option>
                    </select>
                    <input type="text" name="searchKeyword" class="form-control w-auto" value="{{ searchKeyword|default_if_none:'' }}" placeholder="검색어를 입력하세요">
                    <button type="submit" class="btn btn-primary">검색</button>
                    {% if searchType != null %}
                        <a href="{% url 'testapp:list' %}" class="btn btn-danger">취소</a>
                    {% endif %}
                </div>
            </form>        
            <!-- 등록 버튼 -->
            <a href="{% url 'testapp:create' %}" class="btn btn-primary">등록</a>
        </div>
        <!--// 검색, 등록 버튼 -->
    </div>
</div>
<div class="row">
    <div class="col-12">    
        <!-- 등록 버튼 -->
        <div>
            <a href="{% url 'testapp:create' %}" class="btn btn-primary">등록</a>
        </div>
        <!--// 등록 버튼 -->
    </div>
</div>
<div class="row">
    <div class="col-12">
        <!-- 게시글 목록 -->
        <div class="table-responsive">
            <table class="table table-bordered mt-3">
                <thead>
                <tr class="text-center">
                    <th>순번</th>
                    <th>제목</th>
                    <th>글쓴이</th>
                    <th>등록일시</th>
                    <th>수정일시</th>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                    <tr>
                        <td class="text-center">{{ forloop.counter }}</td>
                        <td><a href="{% url 'testapp:read' post_id=post.id %}">{{ post.title }}</a></td>
                        <td class="text-center">{{ post.username }}</td>
                        <td class="text-center">{{ post.created_at | date:"Y-m-d H:i" }}</td>
                        <td class="text-center">{{ post.updated_at | date:"Y-m-d H:i" }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <!--// 게시글 목록 -->
    </div>
</div>
<div class="row">
    <div class="col-12">
        <!-- 페이지네이션 -->
        <div>
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    <!-- 이전 페이지 -->
                    {% if posts.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ posts.previous_page_number }}">이전</a>
                        </li>
                    {% endif %}
                    <!--// 이전 페이지 -->                        
                    <!-- 페이지 리스트 -->
                    {% for page_number in posts.paginator.page_range %}
                        {% if page_number >= posts.number|add:-5 and page_number <= posts.number|add:5 %}
                            <li class="page-item {% if page_number == posts.number %}active{% endif %}">
                                <a class="page-link" href="{% url 'testapp:list' %}?page={{ page_number }}">
                                    {{ page_number }}
                                </a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    <!--// 페이지 리스트 -->        
                    <!-- 다음 페이지 -->
                    {% if posts.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ posts.next_page_number }}">다음</a>
                        </li>
                    {% endif %}
                    <!--// 다음 페이지 -->
                </ul>
              </nav>
        </div>
        <!--// 페이지네이션 -->
    </div>
</div>
{% endblock %}

pycham_test/templates/posts/read.html
{% extends "../base.html" %}

{% block content %}
<div class="row">
    <div class="col-12">
        <!-- 게시글 보기 -->
        <div class="card mb-3">
            <h5 class="card-header text-primary">
                <strong>{{ post.title }}</strong>
            </h5>
            <div class="card-body">  
                <div class="mb-3 text-muted">
                    글쓴이: {{ post.username }} | 등록일시: {{ post.created_at | date:"Y-m-d H:i" }} | 수정일시: {{ post.updated_at | date:"Y-m-d H:i" }}
                </div>

                {% if post.filename %}
                <div class="mb-3 text-muted">
                    첨부 파일: <a href="{% url 'posts:download' post.id %}">{{ post.original_filename }}</a>
                </div>
                {% endif %}

                <div class="mb-3">
                    {{ post.content | linebreaksbr }}
                </div>
            </div>
        </div>
        <div>
            <a href="{% url 'posts:list' %}" class="btn btn-primary">목록</a>
            <a href="{% url 'posts:update' post_id=post.id %}" class="btn btn-warning">수정</a>
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">삭제</button>
        </div>
        <!--// 게시글 보기 -->
    </div>
</div>

<!-- 삭제 모달 -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="deleteForm" action="{% url 'posts:delete' post_id=post.id %}" method="POST">
                {% csrf_token %}
                <div class="modal-header">
                    <h1 class="modal-title fs-5 text-danger" id="deleteModalModalLabel">
                        <strong>게시글 삭제</strong>
                    </h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <p class="text-danger">삭제된 데이터는 복구할 수 없습니다.</p>
                        <p>비밀번호를 입력해주세요.</p>
                    </div>
                    <div>
                        <input type="password" id="password" name="password" placeholder="비밀번호" class="form-control">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-outline-danger">삭제</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- 삭제 모달 -->
{% endblock %}

pycham_test/templates/posts/update.html
{% extends "../base.html" %}

{% block content %}
<div class="row">
    <div class="col-12">
        <!-- 게시글 등록 -->
        <form id="updateForm" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card mb-3">
                <div class="card-header">
                    <span class="text-danger">*</span> 표시는 필수항목입니다.
                </div>
                <div class="card-body">            
                    <div class="mb-3">
                        <label for="title" class="form-label">제목 <span class="text-danger">*</span></label>
                        <input type="text" id="title" name="title" class="form-control" placeholder="제목을 입력하세요." value="{{ form.title.value|default_if_none:'' }}">
                        {% if form.title.errors %}
                        <div class="form-text text-danger">
                            {{ form.title.errors.0 }}
                        </div>
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="content" class="form-label">내용 <span class="text-danger">*</span></label>
                        <textarea rows="10" id="content" name="content" class="form-control" placeholder="내용을 입력하세요.">{{ form.content.value|default_if_none:'' }}</textarea>
                        {% if form.content.errors %}
                        <div class="form-text text-danger">
                            {{ form.content.errors.0 }}
                        </div>
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="username" class="form-label">글쓴이 <span class="text-danger">*</span></label>
                        <input type="text" id="username" name="username" class="form-control" placeholder="글쓴이를 입력하세요." value="{{ form.username.value|default_if_none:'' }}">
                        {% if form.username.errors %}
                        <div class="form-text text-danger">
                            {{ form.username.errors.0 }}
                        </div>
                        {% endif %}
                    </div>
                    <div>
                        <label for="password" class="form-label">비밀번호 <span class="text-danger">*</span></label>
                        <input type="password" id="password" name="password" class="form-control" placeholder="비밀번호를 입력하세요.">
                        {% if form.password.errors %}
                        <div class="form-text text-danger">
                            {{ form.password.errors.0 }}
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% if board.filename %}
                <div class="mb-3">
                    <div class="mb-2">
                        <span>현재 파일: <a href="/board/{{ board.id }}/download">{{ board.original_filename }}</a></span>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="deleteFile" id="deleteFile" value="true">
                        <label class="form-check-label text-danger" for="deleteFile">
                            파일 삭제
                        </label>
                    </div>
                </div>
            {% endif %}
            <div class="mb-3">
                <label class="form-label">첨부 파일</label>
                <input type="file" class="form-control" id="uploadFile" name="uploadFile" accept="*/*">
                <small class="form-text text-muted">새 파일을 선택하면 기존 파일은 자동으로 삭제됩니다.</small>
            </div>
            <div>
                <button type="submit" class="btn btn-primary">등록</button>
                <a href="{% url 'posts:list' %}" class="btn btn-secondary">취소</a>
            </div>
        </form>
        <!--// 게시글 등록 -->
    </div>
</div>
{% endblock %}